CREATE TABLE `listings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `his_listing_id` varchar(45) DEFAULT NULL,
  `url` varchar(700) DEFAULT NULL,
  `resource_id` varchar(200) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `price` float DEFAULT NULL,
  `bedrooms` tinyint(2) DEFAULT NULL,
  `mls` varchar(45) DEFAULT NULL,
  `price/sqft` float DEFAULT NULL,
  `interior_area_size` varchar(45) DEFAULT NULL,
  `year_built` int(11) DEFAULT NULL,
  `lot_size` varchar(45) DEFAULT NULL,
  `land_tenure` varchar(45) DEFAULT NULL,
  `on_market_since` varchar(45) DEFAULT NULL,
  `last_updated` varchar(45) DEFAULT NULL,
  `property_type` varchar(45) DEFAULT NULL,
  `oceanfront` tinyint(1) DEFAULT NULL,
  `description` text,
  `misc_data` longtext,
  `dateFetched` varchar(45) DEFAULT NULL,
  `statusCode` varchar(45) DEFAULT NULL,
  `checksum` varchar(45) DEFAULT NULL,
  `dateTaken` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This is where all current real estate listings will be housed (no pun intended) *okay maybe somewhat intended*';
